services:
  ms-reasignacion:
    build: ./ms-reasignacion
    container_name: cnt-ms-reasignacion
    ports:
      - "8082:8081" # Acceso externo por 8082, interno 8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-ms-reasignacion:3306/db_reasignacion
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rednorte88
    depends_on:
      db-ms-reasignacion:
        condition: service_healthy

  # FALTA AGREGAR EL OTRO SERVICIO AQUÍ PARA QUE LA URL DOCKER FUNCIONE
  ms-lista-espera:
    build: ./ms-lista-espera
    container_name: ms-lista-espera # Este nombre usa el Service en su URL
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-ms-reasignacion:3306/db_lista_espera
    depends_on:
      db-ms-reasignacion:
        condition: service_healthy

  db-ms-reasignacion:
    image: mysql:8.4
    container_name: cnt-db-reasignacion
    # ... resto de tu configuración de salud y volúmenes