spring.application.name=ms-reasignacion
server.port=8081

# Apunta a db_reasignacion
spring.datasource.url=jdbc:mysql://cnt-db-rednorte:3306/db_reasignacion?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=11223344

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true