spring.application.name=ms-bff
server.port=8091

# URLs de los microservicios internos
servicios.usuarios=http://cnt-ms-usuarios:8081
servicios.consultas=http://cnt-ms-consultas:8083
servicios.reasignacion=http://cnt-ms-reasignacion:8081
servicios.ficha=http://cnt-ms-ficha-medica:8084

# Eureka
eureka.client.service-url.defaultZone=http://cnt-eureka-server:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info
