server.port=8095
spring.application.name=ms-estadisticas

eureka.client.service-url.defaultZone=http://cnt-eureka-server:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# URLs internas de los microservicios (dentro de Docker)
ms.consultas.url=http://cnt-ms-consultas:8083
ms.usuarios.url=http://cnt-ms-usuarios:8081
ms.agenda.url=http://cnt-ms-agenda-medica:8094
ms.establecimientos.url=http://cnt-ms-establecimientos:8093

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
